# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy project files into the container
COPY . .

# Upgrade pip and install project dependencies
RUN pip install --upgrade pip \
    && pip install . --no-cache-dir

# Expose any needed ports (if applicable)

# Set the default command to run the MCP server via python module invocation
CMD ["python", "-m", "just_prompt"]
